import { describe, expect, test } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { RunProcessWithCodeTimeout } from "./file-types";
import {
  parseBranchSummary,
  parseGeneratedAttributes,
  parseNumstat,
  parseStatusSummary,
  readDiffFile,
  readDiffSummary,
  statusLabel,
} from "./git-diff";

const runProcessWithCodeTimeout: RunProcessWithCodeTimeout = async (argv) => {
  const process = Bun.spawn(argv, { stdout: "pipe", stderr: "pipe" });
  const [code, stdout, stderr] = await Promise.all([
    process.exited,
    new Response(process.stdout).text(),
    new Response(process.stderr).text(),
  ]);
  return { code, stdout, stderr };
};

function shQuote(value: string) {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

async function git(root: string, ...args: string[]) {
  const result = await runProcessWithCodeTimeout(
    ["git", "-C", root, ...args],
    5000,
  );
  if (result.code !== 0) throw new Error(result.stderr || result.stdout);
  return result.stdout;
}

describe("git diff summary parsing", () => {
  test("labels git statuses", () => {
    expect(statusLabel("A", "staged")).toBe("added");
    expect(statusLabel("D", "unstaged")).toBe("deleted");
    expect(statusLabel("M", "branch")).toBe("modified");
    expect(statusLabel("M", "untracked")).toBe("untracked");
    expect(statusLabel("M", "conflicted")).toBe("conflicted");
  });

  test("parses NUL-separated porcelain status", () => {
    const entries = parseStatusSummary(
      [
        " M src/changed.ts",
        "A  src/staged.ts",
        '?? src/new "file".ts',
        "UU src/conflict.ts",
        "R  src/renamed.ts",
        "src/old.ts",
        "MM both.ts",
        "",
      ].join("\0"),
    );
    expect(entries).toEqual([
      { path: "both.ts", kind: "staged", status: "modified" },
      { path: "both.ts", kind: "unstaged", status: "modified" },
      { path: "src/changed.ts", kind: "unstaged", status: "modified" },
      { path: "src/conflict.ts", kind: "conflicted", status: "conflicted" },
      { path: 'src/new "file".ts', kind: "untracked", status: "untracked" },
      {
        path: "src/renamed.ts",
        old_path: "src/old.ts",
        kind: "staged",
        status: "renamed",
      },
      { path: "src/staged.ts", kind: "staged", status: "added" },
    ]);
  });

  test("parses NUL-separated branch name-status output", () => {
    expect(
      parseBranchSummary(
        ["M", "app.ts", "R100", "old.ts", "new.ts", "D", "gone.ts", ""].join(
          "\0",
        ),
      ),
    ).toEqual([
      { path: "app.ts", kind: "branch", status: "modified" },
      { path: "gone.ts", kind: "branch", status: "deleted" },
      { path: "new.ts", old_path: "old.ts", kind: "branch", status: "renamed" },
    ]);
  });

  test("parses numstat, renames, and binary files", () => {
    const stats = parseNumstat(
      [
        "3\t1\tapp.ts",
        "0\t0\t",
        "old.ts",
        "new.ts",
        "-\t-\timage.png",
        "",
      ].join("\0"),
    );
    expect(Object.fromEntries(stats)).toEqual({
      "app.ts": { additions: 3, deletions: 1 },
      "new.ts": { additions: 0, deletions: 0 },
      "image.png": { additions: 0, deletions: 0 },
    });
  });

  test("recognizes files marked generated by Git attributes", () => {
    const output = [
      "dist/app.js",
      "linguist-generated",
      "true",
      "src/app.ts",
      "linguist-generated",
      "unspecified",
      "vendor/schema.ts",
      "linguist-generated",
      "set",
      "",
    ].join("\0");
    expect(Array.from(parseGeneratedAttributes(output))).toEqual([
      "dist/app.js",
      "vendor/schema.ts",
    ]);
  });
});

describe("git diff in a repository", () => {
  test("lists and diffs working-tree and branch changes", async () => {
    const root = await mkdtemp(join(tmpdir(), "thyra-git-diff-"));
    try {
      await git(root, "init", "-b", "main");
      await git(root, "config", "user.email", "test@example.com");
      await git(root, "config", "user.name", "Thyra Test");
      await writeFile(join(root, "app.ts"), "one\n");
      await writeFile(
        join(root, ".gitattributes"),
        "gen.js linguist-generated\n",
      );
      await git(root, "add", ".");
      await git(root, "commit", "-m", "init");
      await git(root, "checkout", "-b", "feature");
      await writeFile(join(root, "app.ts"), "one\ntwo\n");
      await git(root, "commit", "-am", "two");
      await writeFile(join(root, "app.ts"), "one\ntwo\nthree\n");
      await writeFile(join(root, "new file.txt"), "a\nb\n");
      await writeFile(join(root, "gen.js"), "x\n");
      const context = { root, shQuote, runProcessWithCodeTimeout };

      const working = await readDiffSummary({
        ...context,
        workspaceId: "w1",
        workspace: { label: "Repo" },
        params: {},
      });
      expect(working.mode).toBe("working");
      expect(working.entries).toEqual([
        {
          path: "app.ts",
          kind: "unstaged",
          status: "modified",
          additions: 1,
          deletions: 0,
        },
        {
          path: "gen.js",
          kind: "untracked",
          status: "untracked",
          additions: 1,
          deletions: 0,
          generated: true,
        },
        {
          path: "new file.txt",
          kind: "untracked",
          status: "untracked",
          additions: 2,
          deletions: 0,
        },
      ]);
      expect(working.counts).toMatchObject({ unstaged: 1, untracked: 2 });

      const untracked = await readDiffFile({
        ...context,
        workspaceId: "w1",
        params: { path: "new file.txt", kind: "untracked" },
      });
      expect(untracked.diff).toContain("+b");

      const branch = await readDiffSummary({
        ...context,
        workspaceId: "w1",
        workspace: {},
        params: { mode: "branch-main" },
      });
      expect(branch.base).toBe("main");
      expect(branch.entries).toEqual([
        {
          path: "app.ts",
          kind: "branch",
          status: "modified",
          additions: 1,
          deletions: 0,
        },
      ]);
      const branchFile = await readDiffFile({
        ...context,
        workspaceId: "w1",
        params: { path: "app.ts", mode: "branch-main" },
      });
      expect(branchFile.kind).toBe("branch");
      expect(branchFile.diff).toContain("+two");
      expect(branchFile.diff).not.toContain("+three");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
