import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { dirname as win32Dirname } from "node:path/win32";
import {
  escapeSystemdExecPath,
  resolveServicePlatform,
  type ServicePlatform,
  xmlEscape,
} from "../config/service-definitions";
import {
  bootoutLaunchdService,
  type LaunchdTiming,
  launchdServiceLoaded,
  replaceLaunchdService,
} from "../config/launchd";
import {
  defaultRunCommand,
  queryWindowsTask,
  registerWindowsTask,
  restartWindowsTask,
  type RunCommand,
} from "../config/service-manager";

export const HERDR_SERVICE_MARKER = "Generated by thyra herdr setup.";
export const HERDR_SERVICE_LABEL = "dev.thyra.herdr";

export interface HerdrServicePaths {
  definition: string;
  taskName?: string;
  stdoutLog?: string;
  stderrLog?: string;
}

export interface HerdrServiceDeps {
  platform?: ServicePlatform;
  homeDir?: string;
  appDataDir?: string;
  uid?: number;
  runCommand?: RunCommand;
  launchd?: LaunchdTiming;
  /**
   * The binary supports `herdr server --adopt` (see `probeHerdrSupervision`).
   * launchd then supervises it across live handoffs and adopts a server that
   * is already running instead of failing with "already running".
   */
  adopt?: boolean;
}

export function resolveHerdrServicePaths(
  platform: ServicePlatform,
  homeDir: string,
  appDataDir?: string,
): HerdrServicePaths {
  if (platform === "windows-task") {
    const base = join(
      appDataDir ?? join(homeDir, "AppData", "Roaming"),
      "thyra",
    );
    const userKey = createHash("sha256")
      .update(base.toLowerCase())
      .digest("hex")
      .slice(0, 16);
    return {
      definition: join(base, "herdr-task.ps1"),
      taskName: `${HERDR_SERVICE_LABEL}-${userKey}`,
    };
  }
  if (platform === "systemd") {
    return {
      definition: join(
        homeDir,
        ".config",
        "systemd",
        "user",
        "thyra-herdr.service",
      ),
    };
  }
  return {
    definition: join(
      homeDir,
      "Library",
      "LaunchAgents",
      `${HERDR_SERVICE_LABEL}.plist`,
    ),
    stdoutLog: join(homeDir, "Library", "Logs", "thyra-herdr.stdout.log"),
    stderrLog: join(homeDir, "Library", "Logs", "thyra-herdr.stderr.log"),
  };
}

export function renderHerdrSystemdService(binaryPath: string): string {
  return `# ${HERDR_SERVICE_MARKER}
[Unit]
Description=Herdr server (managed by Thyra)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=${escapeSystemdExecPath(binaryPath)} server
Restart=always
RestartSec=2
TimeoutStopSec=15

[Install]
WantedBy=default.target
`;
}

/**
 * With `adopt`, the job runs `herdr server --adopt`: the launchd-tracked
 * process stays alive as a small anchor across live handoffs and exits 0 only
 * after an intentional stop, so KeepAlive restarts it only after a crash, and
 * an "already running" start adopts that server instead of spinning. Without
 * it (a Herdr build that lacks `--adopt`), a live handoff leaves the server
 * unsupervised.
 */
export function renderHerdrLaunchdService(
  binaryPath: string,
  paths: HerdrServicePaths,
  options: { adopt?: boolean } = {},
): string {
  const programArguments = [
    binaryPath,
    "server",
    ...(options.adopt ? ["--adopt"] : []),
  ]
    .map((argument) => `    <string>${xmlEscape(argument)}</string>`)
    .join("\n");
  const keepAlive = options.adopt
    ? `<dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>`
    : "<true/>";
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${HERDR_SERVICE_MARKER} -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${HERDR_SERVICE_LABEL}</string>

  <key>ProgramArguments</key>
  <array>
${programArguments}
  </array>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  ${keepAlive}
  <key>ThrottleInterval</key>
  <integer>${options.adopt ? 10 : 2}</integer>
  <key>ProcessType</key>
  <string>Background</string>

  <key>StandardOutPath</key>
  <string>${xmlEscape(paths.stdoutLog ?? "")}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(paths.stderrLog ?? "")}</string>
</dict>
</plist>
`;
}

function powershellSingleQuotedString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function renderHerdrWindowsTask(
  binaryPath: string,
  paths: HerdrServicePaths,
): string {
  if (!paths.taskName) throw new Error("Windows service task name is missing");
  const taskName = powershellSingleQuotedString(paths.taskName);
  const executable = powershellSingleQuotedString(binaryPath);
  const argument = powershellSingleQuotedString("server");
  const workingDirectory = powershellSingleQuotedString(
    win32Dirname(binaryPath),
  );

  return `\uFEFF# ${HERDR_SERVICE_MARKER}
$ErrorActionPreference = "Stop"
$taskName = ${taskName}
$user = [Security.Principal.WindowsIdentity]::GetCurrent().Name
$action = New-ScheduledTaskAction -Execute ${executable} -Argument ${argument} -WorkingDirectory ${workingDirectory}
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $user
$principal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1)
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
`;
}

function assertHerdrDefinitionWritable(path: string) {
  if (
    existsSync(path) &&
    !readFileSync(path, "utf8").includes(HERDR_SERVICE_MARKER)
  ) {
    throw new Error(
      `${path} was not generated by thyra; remove it yourself before rerunning herdr setup`,
    );
  }
}

function writeHerdrDefinition(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  const temporaryPath = `${path}.tmp-${process.pid}`;
  try {
    writeFileSync(temporaryPath, content, { mode: 0o644 });
    renameSync(temporaryPath, path);
  } finally {
    rmSync(temporaryPath, { force: true });
  }
}

function resolveDeps(deps: HerdrServiceDeps) {
  const platform = deps.platform ?? resolveServicePlatform(process.platform);
  return {
    platform,
    homeDir: deps.homeDir ?? homedir(),
    appDataDir: deps.appDataDir ?? process.env.APPDATA,
    uid: deps.uid ?? process.getuid?.(),
    runCommand: deps.runCommand ?? defaultRunCommand,
    launchd: deps.launchd ?? {},
  };
}

function assertRunSucceeded(code: number, operation: string) {
  if (code !== 0) {
    throw new Error(`${operation} failed (exit ${code})`);
  }
}

/**
 * Install (or replace) the user service running `herdr server` and start it.
 * The unit is regenerated on every call so a changed binary path takes effect.
 */
export function installHerdrService(
  binaryPath: string,
  deps: HerdrServiceDeps = {},
): HerdrServicePaths {
  const { platform, homeDir, appDataDir, uid, runCommand, launchd } =
    resolveDeps(deps);
  const paths = resolveHerdrServicePaths(platform, homeDir, appDataDir);
  assertHerdrDefinitionWritable(paths.definition);
  if (paths.stdoutLog) mkdirSync(dirname(paths.stdoutLog), { recursive: true });

  if (platform === "systemd") {
    writeHerdrDefinition(
      paths.definition,
      renderHerdrSystemdService(binaryPath),
    );
    assertRunSucceeded(
      runCommand(["systemctl", "--user", "daemon-reload"]),
      "systemd daemon-reload",
    );
    assertRunSucceeded(
      runCommand(["systemctl", "--user", "enable", "thyra-herdr.service"]),
      "systemd service enable",
    );
    // Explicit restart: `enable` does not restart an already-active service.
    assertRunSucceeded(
      runCommand(["systemctl", "--user", "restart", "thyra-herdr.service"]),
      "systemd service start",
    );
    return paths;
  }

  if (platform === "launchd") {
    if (uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    writeHerdrDefinition(
      paths.definition,
      renderHerdrLaunchdService(binaryPath, paths, { adopt: deps.adopt }),
    );
    const domain = `gui/${uid}`;
    assertRunSucceeded(
      replaceLaunchdService(
        domain,
        `${domain}/${HERDR_SERVICE_LABEL}`,
        paths.definition,
        runCommand,
        launchd,
      ),
      "launchd service start",
    );
    return paths;
  }

  writeHerdrDefinition(
    paths.definition,
    renderHerdrWindowsTask(binaryPath, paths),
  );
  assertRunSucceeded(
    registerWindowsTask(paths.definition, runCommand),
    "scheduled task registration",
  );
  assertRunSucceeded(
    restartWindowsTask(paths.taskName ?? "", runCommand),
    "scheduled task start",
  );
  return paths;
}

/**
 * Stop and remove the user service generated by `thyra herdr setup`.
 * Definitions without the Thyra marker are never touched. Stopping the
 * server ends its panes; the Herdr binary and its session data are kept.
 */
export function uninstallHerdrService(deps: HerdrServiceDeps = {}): {
  removed: boolean;
  definition: string;
} {
  const { platform, homeDir, appDataDir, uid, runCommand, launchd } =
    resolveDeps(deps);
  const paths = resolveHerdrServicePaths(platform, homeDir, appDataDir);
  const definitionExists = existsSync(paths.definition);
  if (
    definitionExists &&
    !readFileSync(paths.definition, "utf8").includes(HERDR_SERVICE_MARKER)
  ) {
    throw new Error(
      `${paths.definition} was not generated by thyra and will not be removed`,
    );
  }

  if (platform === "systemd") {
    if (!definitionExists)
      return { removed: false, definition: paths.definition };
    assertRunSucceeded(
      runCommand([
        "systemctl",
        "--user",
        "disable",
        "--now",
        "thyra-herdr.service",
      ]),
      "systemd service stop",
    );
    rmSync(paths.definition, { force: true });
    assertRunSucceeded(
      runCommand(["systemctl", "--user", "daemon-reload"]),
      "systemd daemon-reload",
    );
    return { removed: true, definition: paths.definition };
  }

  if (platform === "launchd") {
    if (!definitionExists)
      return { removed: false, definition: paths.definition };
    if (uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    const service = `gui/${uid}/${HERDR_SERVICE_LABEL}`;
    if (launchdServiceLoaded(service, runCommand)) {
      assertRunSucceeded(
        bootoutLaunchdService(service, runCommand, launchd),
        "launchd service stop",
      );
    }
    rmSync(paths.definition, { force: true });
    return { removed: true, definition: paths.definition };
  }

  const taskName = paths.taskName ?? "";
  const query = queryWindowsTask(taskName, runCommand);
  if (query.status === "error") {
    throw new Error(`scheduled task query failed (exit ${query.code})`);
  }
  if (query.status === "missing" && !definitionExists) {
    return { removed: false, definition: paths.definition };
  }
  if (query.status === "exists") {
    if (!definitionExists) {
      throw new Error(
        `scheduled task ${taskName} was not created by thyra and will not be removed`,
      );
    }
    runCommand(["schtasks.exe", "/End", "/TN", taskName], { quiet: true });
    assertRunSucceeded(
      runCommand(["schtasks.exe", "/Delete", "/TN", taskName, "/F"]),
      "scheduled task removal",
    );
  }
  rmSync(paths.definition, { force: true });
  return { removed: true, definition: paths.definition };
}

export function herdrServiceStatus(deps: HerdrServiceDeps = {}): {
  installed: boolean;
  active: boolean;
} {
  const { platform, homeDir, appDataDir, uid, runCommand } = resolveDeps(deps);
  const paths = resolveHerdrServicePaths(platform, homeDir, appDataDir);
  const installed = existsSync(paths.definition);
  if (platform === "systemd") {
    return {
      installed,
      active:
        runCommand(
          [
            "systemctl",
            "--user",
            "is-active",
            "--quiet",
            "thyra-herdr.service",
          ],
          { quiet: true },
        ) === 0,
    };
  }
  if (platform === "launchd") {
    if (uid === undefined) return { installed, active: false };
    return {
      installed,
      active:
        runCommand(
          ["launchctl", "print", `gui/${uid}/${HERDR_SERVICE_LABEL}`],
          { quiet: true },
        ) === 0,
    };
  }
  if (!paths.taskName) return { installed, active: false };
  const query = queryWindowsTask(paths.taskName, runCommand);
  return { installed, active: query.status === "exists" && query.active };
}

/** `herdr server supervision` output, from a build that supports `--adopt`. */
export interface HerdrSupervision {
  adopt: boolean;
  server: { pid: number; state: "running" | "stopped"; alive: boolean } | null;
  supervisor_pid: number | null;
}

export type CaptureCommand = (argv: string[]) => {
  code: number;
  stdout: string;
};

export function defaultCaptureCommand(argv: string[]) {
  const result = Bun.spawnSync(argv, {
    stdin: "ignore",
    stdout: "pipe",
    stderr: "ignore",
  });
  return { code: result.exitCode ?? 1, stdout: result.stdout.toString() };
}

/**
 * Asks the binary for its supervision state. Builds without `--adopt` reject
 * the subcommand, which yields null.
 */
export function probeHerdrSupervision(
  binaryPath: string,
  capture: CaptureCommand = defaultCaptureCommand,
): HerdrSupervision | null {
  let result: { code: number; stdout: string };
  try {
    result = capture([binaryPath, "server", "supervision"]);
  } catch {
    return null;
  }
  if (result.code !== 0) return null;
  try {
    const parsed = JSON.parse(result.stdout.trim()) as HerdrSupervision;
    return parsed && parsed.adopt === true ? parsed : null;
  } catch {
    return null;
  }
}

/** Whether the managed launchd job is loaded (only meaningful on macOS). */
export function herdrLaunchdServiceLoaded(
  deps: HerdrServiceDeps = {},
): boolean {
  const { uid, runCommand } = resolveDeps(deps);
  if (uid === undefined) return false;
  return launchdServiceLoaded(`gui/${uid}/${HERDR_SERVICE_LABEL}`, runCommand);
}
