import { afterEach, describe, expect, test } from "bun:test";
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import {
  runServiceCommand as runServiceCommandUnmocked,
  queryWindowsTask,
  SERVICE_COMMAND_CONTINUE,
} from "./service-manager";
import {
  renderLaunchdService,
  renderSystemdService,
  renderWindowsTaskDefinition,
  resolveServicePaths,
} from "./service-definitions";

// Never let a test reach the real service manager by accident.
function runServiceCommand(
  args: string[],
  dependencies: Parameters<typeof runServiceCommandUnmocked>[1] = {},
) {
  return runServiceCommandUnmocked(args, {
    runCommand: () => {
      throw new Error("native commands must be mocked");
    },
    ...dependencies,
  });
}

const tempDirs: string[] = [];

function tempHome(): string {
  const path = mkdtempSync(join(tmpdir(), "thyra-service-"));
  tempDirs.push(path);
  return path;
}

function isWindowsTaskQuery(argv: string[]): boolean {
  const script = argv.at(-1) ?? "";
  return (
    argv[0] === "powershell.exe" &&
    argv.includes("-Command") &&
    script.includes("CmdletizationQuery_NotFound_TaskName") &&
    script.includes("$taskInfo.State -eq 'Running'")
  );
}

function isWindowsTaskWait(argv: string[]): boolean {
  const script = argv.at(-1) ?? "";
  return (
    argv[0] === "powershell.exe" &&
    argv.includes("-Command") &&
    script.includes("Get-ScheduledTask") &&
    script.includes("AddSeconds(15)")
  );
}

afterEach(() => {
  for (const path of tempDirs.splice(0)) {
    rmSync(path, { recursive: true, force: true });
  }
});

test("Windows task queries distinguish registration from running state", () => {
  for (const [code, expected] of [
    [0, { status: "exists", active: true }],
    [4, { status: "exists", active: false }],
    [3, { status: "missing" }],
    [5, { status: "error", code: 5 }],
  ] as const) {
    expect(
      queryWindowsTask("Herdr's task", (argv) => {
        const script = argv.at(-1)!;
        expect(script).toContain("-TaskName 'Herdr''s task'");
        expect(script).toContain(
          "if ($taskInfo.State -eq 'Running') { exit 0 }; exit 4",
        );
        return code;
      }),
    ).toEqual(expected);
  }
});

describe("service definition rendering", () => {
  test("escapes systemd paths without quoting them", () => {
    const definition = renderSystemdService(
      "/opt/Herdr % GUI/thyra",
      "/srv/herdr gui/config/thyra.env",
    );

    expect(definition).toContain(
      "EnvironmentFile=-/srv/herdr\\x20gui/config/thyra.env",
    );
    expect(definition).not.toContain('EnvironmentFile="');
    expect(definition).toContain(
      "EnvironmentFile=-/srv/herdr\\x20gui/config/auth-providers.env",
    );
    expect(definition).toContain("ExecStart=/opt/Herdr\\x20%%\\x20GUI/thyra");
    expect(definition).not.toContain('ExecStart="');
    expect(definition).toContain("Restart=always");
  });

  test("passes launchd paths as arguments without interpolating shell code", () => {
    const definition = renderLaunchdService("/Applications/Herdr & GUI", {
      config: "/srv/herdr & gui/config/thyra.env",
      definition: "/unused.plist",
      stdoutLog: "/srv/herdr & gui/logs/out.log",
      stderrLog: "/srv/herdr & gui/logs/error.log",
    });

    expect(definition).toContain(
      "<string>/Applications/Herdr &amp; GUI</string>",
    );
    expect(definition).toContain(
      "<string>/srv/herdr &amp; gui/config/thyra.env</string>",
    );
    expect(definition).toContain("<key>KeepAlive</key>");
    expect(definition).not.toContain("RESTART_SUPERVISOR");
    expect(definition).toContain("exec &quot;$2&quot;");
  });

  test("renders a direct-executable Windows login task", () => {
    const definition = renderWindowsTaskDefinition(
      "C:\\Program Files\\Herdr's GUI\\thyra.exe",
      {
        config: "C:\\Users\\tester\\AppData\\Roaming\\thyra\\thyra.env",
        definition: "C:\\unused.ps1",
        taskName: "dev.thyra-test-user",
      },
    );

    expect(definition.charCodeAt(0)).toBe(0xfeff);
    expect(definition).toContain(
      "New-ScheduledTaskAction -Execute 'C:\\Program Files\\Herdr''s GUI\\thyra.exe'",
    );
    expect(definition).toContain(
      'service run "C:\\Users\\tester\\AppData\\Roaming\\thyra\\thyra.env"',
    );
    expect(definition).toContain("$taskName = 'dev.thyra-test-user'");
    expect(definition).toContain("-AllowStartIfOnBatteries");
    expect(definition).toContain("Generated by thyra service install.");
  });

  test("isolates Windows task names by user config directory", () => {
    const first = resolveServicePaths(
      "windows-task",
      "C:\\Users\\first",
      "C:\\Users\\first\\AppData\\Roaming",
    );
    const second = resolveServicePaths(
      "windows-task",
      "C:\\Users\\second",
      "C:\\Users\\second\\AppData\\Roaming",
    );

    expect(first.taskName).toStartWith("dev.thyra-");
    expect(first.taskName).not.toBe(second.taskName);
  });
});

describe("service commands", () => {
  test("installs and starts a systemd user service", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const commands: Array<{ argv: string[]; quiet: boolean }> = [];
    const logs: string[] = [];
    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/thyra-test/bin/thyra",
        argv: ["/opt/thyra-test/bin/thyra", "service", "install"],
        uid: 1000,
      },
      runCommand: (argv, options) => {
        commands.push({ argv, quiet: options?.quiet === true });
        return 0;
      },
      getLanIPs: () => ["192.0.2.23"],
      log: (message) => logs.push(message),
    });

    expect(code).toBe(0);
    expect(commands).toEqual([
      {
        argv: ["systemctl", "--user", "daemon-reload"],
        quiet: false,
      },
      {
        argv: ["systemctl", "--user", "enable", "thyra.service"],
        quiet: false,
      },
      {
        argv: ["systemctl", "--user", "restart", "thyra.service"],
        quiet: false,
      },
    ]);
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "thyra.service",
    );
    const configPath = join(homeDir, ".config", "thyra", "thyra.env");
    expect(readFileSync(definitionPath, "utf8")).toContain(
      "ExecStart=/opt/thyra-test/bin/thyra",
    );
    expect(readFileSync(configPath, "utf8")).toContain("HOST=0.0.0.0");
    expect(statSync(configPath).mode & 0o777).toBe(0o600);
    // Browsers log in with passkeys; install never creates a shared token.
    expect(existsSync(join(homeDir, ".config", "thyra", "auth-token"))).toBe(
      false,
    );
    expect(logs.join("\n")).toContain("Installed systemd service");
    expect(logs).toContain("Open: http://localhost:8787");
    expect(logs).toContain("LAN: http://192.0.2.23:8787");
    expect(logs.join("\n")).toContain("thyra user add <name> --admin");
  });

  test("reloads the systemd definition before restarting", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "thyra.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(definitionPath, "[Service]\nExecStart=/bin/true\n");
    const commands: string[][] = [];

    const code = runServiceCommand(["service", "reload"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/thyra-test/bin/thyra",
        argv: ["/opt/thyra-test/bin/thyra", "service", "reload"],
      },
      runCommand: (argv) => {
        commands.push(argv);
        return 0;
      },
    });

    expect(code).toBe(0);
    expect(commands).toEqual([
      ["systemctl", "--user", "daemon-reload"],
      ["systemctl", "--user", "restart", "thyra.service"],
    ]);
  });

  test("does not restart systemd when daemon-reload fails", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "thyra.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(definitionPath, "[Service]\nExecStart=/bin/true\n");
    let commandCount = 0;

    const code = runServiceCommand(["service", "reload"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/thyra-test/bin/thyra",
        argv: ["/opt/thyra-test/bin/thyra", "service", "reload"],
      },
      runCommand: () => {
        commandCount += 1;
        return 5;
      },
    });

    expect(code).toBe(5);
    expect(commandCount).toBe(1);
  });

  test("reports a missing service definition during reload", () => {
    const errors: string[] = [];
    let commandCount = 0;

    const code = runServiceCommand(["service", "reload"], {
      runtime: {
        platform: "linux",
        homeDir: tempHome(),
        execPath: "/opt/thyra-test/bin/thyra",
        argv: ["/opt/thyra-test/bin/thyra", "service", "reload"],
      },
      runCommand: () => {
        commandCount += 1;
        return 0;
      },
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(commandCount).toBe(0);
    expect(errors.join("\n")).toContain(
      "cannot reload missing systemd service",
    );
  });

  test("preserves an existing environment file during reinstall", () => {
    const homeDir = tempHome();
    const configPath = join(homeDir, ".config", "thyra", "thyra.env");
    mkdirSync(join(homeDir, ".config", "thyra"), { recursive: true });
    writeFileSync(configPath, "HOST=0.0.0.0\nTHYRA_PASSWORD=secret\n");
    chmodSync(configPath, 0o644);

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/usr/local/bin/thyra",
        argv: ["/usr/local/bin/thyra", "service", "install"],
      },
      runCommand: () => 0,
      log: () => undefined,
    });

    expect(code).toBe(0);
    expect(readFileSync(configPath, "utf8")).toBe(
      "HOST=0.0.0.0\nTHYRA_PASSWORD=secret\n",
    );
    if (process.platform !== "win32") {
      expect(statSync(configPath).mode & 0o777).toBe(0o600);
    }
    expect(existsSync(join(homeDir, ".config", "thyra", "auth-token"))).toBe(
      false,
    );
  });

  test("preserves a managed custom wrapper command", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "thyra.service",
    );
    const binaryPath = join(homeDir, ".local", "bin", "thyra");
    const wrapperPath = join(homeDir, ".local", "libexec", "service-wrapper");
    const wrapperCommand =
      `${wrapperPath} --service example -- ` + `${binaryPath} --host 0.0.0.0`;
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(
      definitionPath,
      `# Generated by thyra service install.\n` +
        `[Service]\nExecStart=${wrapperCommand}\n`,
    );
    const logs: string[] = [];

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: binaryPath,
        argv: [binaryPath, "service", "install"],
      },
      runCommand: () => 0,
      getLanIPs: () => [],
      log: (message) => logs.push(message),
    });

    expect(code).toBe(0);
    const definition = readFileSync(definitionPath, "utf8");
    expect(definition).toContain(`ExecStart=${wrapperCommand}`);
    expect(definition).toContain("Restart=always");
    expect(logs).toContain(`Preserved custom ExecStart: ${wrapperCommand}`);
  });

  test("replaces a stale custom command that does not invoke this binary", () => {
    if (process.platform === "win32") return;
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "thyra.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(
      definitionPath,
      `# Generated by thyra service install.\n` +
        `[Service]\n` +
        `ExecStart=/usr/local/bin/service-wrapper -- ` +
        `/opt/thyra-test/bin/thyra-old\n`,
    );

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/opt/thyra-test/bin/thyra",
        argv: ["/opt/thyra-test/bin/thyra", "service", "install"],
      },
      runCommand: () => 0,
      getLanIPs: () => [],
      log: () => undefined,
    });

    expect(code).toBe(0);
    expect(readFileSync(definitionPath, "utf8")).toContain(
      "ExecStart=/opt/thyra-test/bin/thyra",
    );
  });

  test("refuses to overwrite an unmanaged service without force", () => {
    const homeDir = tempHome();
    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "thyra.service",
    );
    mkdirSync(join(homeDir, ".config", "systemd", "user"), {
      recursive: true,
    });
    writeFileSync(definitionPath, "[Service]\nExecStart=/custom/wrapper\n");
    const errors: string[] = [];
    let commandCount = 0;

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "linux",
        homeDir,
        execPath: "/usr/local/bin/thyra",
        argv: ["/usr/local/bin/thyra", "service", "install"],
      },
      runCommand: () => {
        commandCount += 1;
        return 0;
      },
      log: () => undefined,
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(commandCount).toBe(0);
    expect(readFileSync(definitionPath, "utf8")).toContain("/custom/wrapper");
    expect(errors.join("\n")).toContain("rerun with --force");
  });

  test("validates launchd identity before writing service files", () => {
    const homeDir = tempHome();
    const errors: string[] = [];

    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "darwin",
        homeDir,
        execPath: "/opt/thyra-test/bin/thyra",
        argv: ["/opt/thyra-test/bin/thyra"],
      },
      runCommand: () => {
        throw new Error("should not run");
      },
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(errors.join("\n")).toContain(
      "cannot determine the current user id for launchd",
    );
    expect(() =>
      readFileSync(join(homeDir, ".config", "thyra", "thyra.env"), "utf8"),
    ).toThrow();
    expect(() =>
      readFileSync(
        join(homeDir, "Library", "LaunchAgents", "dev.thyra.plist"),
        "utf8",
      ),
    ).toThrow();
  });

  test("installs, inspects, restarts, reloads, and removes a launchd agent", () => {
    const homeDir = tempHome();
    const commands: Array<{ argv: string[]; quiet: boolean }> = [];
    const runtime = {
      platform: "darwin",
      homeDir,
      execPath: "/opt/thyra-test/bin/thyra",
      argv: ["/opt/thyra-test/bin/thyra"],
      uid: 501,
    };
    let launchdLoaded = false;
    const runCommand = (argv: string[], options?: { quiet?: boolean }) => {
      commands.push({ argv, quiet: options?.quiet === true });
      if (argv[1] === "print") return launchdLoaded ? 0 : 1;
      if (argv[1] === "bootstrap") launchdLoaded = true;
      if (argv[1] === "bootout") launchdLoaded = false;
      return 0;
    };

    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "status"], {
        runtime,
        runCommand,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "restart"], {
        runtime,
        runCommand,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "reload"], {
        runtime,
        runCommand,
      }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);

    const plistPath = join(
      homeDir,
      "Library",
      "LaunchAgents",
      "dev.thyra.plist",
    );
    expect(() => readFileSync(plistPath, "utf8")).toThrow();
    expect(commands).toEqual([
      {
        argv: ["launchctl", "print", "gui/501/dev.thyra"],
        quiet: true,
      },
      {
        argv: ["launchctl", "bootstrap", "gui/501", plistPath],
        quiet: false,
      },
      {
        argv: ["launchctl", "print", "gui/501/dev.thyra"],
        quiet: false,
      },
      {
        argv: ["launchctl", "kickstart", "-k", "gui/501/dev.thyra"],
        quiet: false,
      },
      {
        argv: ["launchctl", "print", "gui/501/dev.thyra"],
        quiet: true,
      },
      {
        argv: ["launchctl", "bootout", "gui/501/dev.thyra"],
        quiet: false,
      },
      {
        argv: ["launchctl", "bootstrap", "gui/501", plistPath],
        quiet: false,
      },
      {
        argv: ["launchctl", "print", "gui/501/dev.thyra"],
        quiet: true,
      },
      {
        argv: ["launchctl", "bootout", "gui/501/dev.thyra"],
        quiet: false,
      },
    ]);
    expect(
      readFileSync(join(homeDir, ".config", "thyra", "thyra.env"), "utf8"),
    ).toContain("HOST=0.0.0.0");
  });

  test("manages a Windows login task", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const executable = join(homeDir, "bin", "thyra.exe");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    const definitionPath = paths.definition;
    const configPath = paths.config;
    const taskName = paths.taskName!;
    const runtime = {
      platform: "win32",
      homeDir,
      appDataDir,
      execPath: executable,
      argv: [executable],
    };
    const commands: Array<{ argv: string[]; quiet: boolean }> = [];
    let taskExists = false;
    const runCommand = (argv: string[], options?: { quiet?: boolean }) => {
      commands.push({ argv, quiet: options?.quiet === true });
      if (isWindowsTaskQuery(argv)) return taskExists ? 0 : 3;
      if (argv.includes("-File")) taskExists = true;
      if (argv[1] === "/Delete") taskExists = false;
      return 0;
    };

    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);
    const definition = readFileSync(definitionPath, "utf8");
    expect(definition.charCodeAt(0)).toBe(0xfeff);
    expect(definition).toContain(
      `New-ScheduledTaskAction -Execute '${executable}'`,
    );
    expect(definition).toContain(`service run "${configPath}"`);
    expect(readFileSync(configPath, "utf8")).toContain("HOST=0.0.0.0");
    expect(existsSync(join(appDataDir, "thyra", "auth-token"))).toBe(false);

    expect(
      runServiceCommand(["service", "status"], { runtime, runCommand }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "restart"], { runtime, runCommand }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "reload"], { runtime, runCommand }),
    ).toBe(0);
    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime,
        runCommand,
        log: () => undefined,
      }),
    ).toBe(0);

    expect(isWindowsTaskQuery(commands[0].argv)).toBeTrue();
    expect(commands[0].quiet).toBeFalse();
    expect(commands[0].argv.at(-1)).toContain(taskName);
    expect(commands.find(({ argv }) => argv.includes("-File"))?.argv).toEqual([
      "powershell.exe",
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      definitionPath,
    ]);
    expect(commands.filter(({ argv }) => argv.includes("-File"))).toHaveLength(
      2,
    );
    expect(commands.filter(({ argv }) => argv[1] === "/Run")).toHaveLength(3);
    expect(
      commands
        .filter(({ argv }) => argv.includes("/TN"))
        .every(({ argv }) => argv[argv.indexOf("/TN") + 1] === taskName),
    ).toBeTrue();
    expect(commands.some(({ argv }) => isWindowsTaskWait(argv))).toBeTrue();
    expect(commands.some(({ argv }) => argv[1] === "/Delete")).toBeTrue();
    expect(taskExists).toBeFalse();
    expect(existsSync(definitionPath)).toBeFalse();
    expect(existsSync(configPath)).toBeTrue();
  });

  test("uninstalls an inactive Windows task when its helper script is missing", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    const taskName = paths.taskName!;
    const commands: string[][] = [];
    let taskExists = true;

    const code = runServiceCommand(["service", "uninstall"], {
      runtime: {
        platform: "win32",
        homeDir,
        appDataDir,
        execPath: join(homeDir, "thyra.exe"),
        argv: [],
      },
      runCommand: (argv) => {
        commands.push(argv);
        if (isWindowsTaskQuery(argv)) return taskExists ? 4 : 3;
        if (argv[1] === "/Delete") {
          taskExists = false;
          return 1;
        }
        return 0;
      },
      log: () => undefined,
    });

    expect(code).toBe(0);
    expect(commands.some((argv) => argv[1] === "/End")).toBeTrue();
    expect(commands.some((argv) => argv[1] === "/Delete")).toBeTrue();
    expect(commands.filter(isWindowsTaskQuery)).toHaveLength(2);
    expect(taskExists).toBeFalse();
    expect(existsSync(paths.definition)).toBeFalse();
    expect(
      commands
        .filter((argv) => argv.includes("/TN"))
        .every((argv) => argv[argv.indexOf("/TN") + 1] === taskName),
    ).toBeTrue();
  });

  test("removes a stale Windows helper when its task is already absent", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    mkdirSync(dirname(paths.definition), { recursive: true });
    writeFileSync(paths.definition, "# Generated by thyra service install.\n");
    const commands: string[][] = [];

    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime: {
          platform: "win32",
          homeDir,
          appDataDir,
          execPath: join(homeDir, "thyra.exe"),
          argv: [],
        },
        runCommand: (argv) => {
          commands.push(argv);
          return isWindowsTaskQuery(argv) ? 3 : 0;
        },
        log: () => undefined,
      }),
    ).toBe(0);

    expect(commands.filter(isWindowsTaskQuery)).toHaveLength(1);
    expect(commands.some((argv) => argv[1] === "/Delete")).toBeFalse();
    expect(existsSync(paths.definition)).toBeFalse();
  });

  test("propagates Windows task query failures without changing state", () => {
    const homeDir = tempHome();
    const appDataDir = join(homeDir, "AppData", "Roaming");
    const executable = join(homeDir, "thyra.exe");
    const paths = resolveServicePaths("windows-task", homeDir, appDataDir);
    const runtime = {
      platform: "win32",
      homeDir,
      appDataDir,
      execPath: executable,
      argv: [executable],
    };
    const installCommands: string[][] = [];

    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand: (argv) => {
          installCommands.push(argv);
          return isWindowsTaskQuery(argv) ? 5 : 0;
        },
        log: () => undefined,
      }),
    ).toBe(5);
    expect(installCommands).toHaveLength(1);
    expect(isWindowsTaskQuery(installCommands[0])).toBeTrue();
    expect(existsSync(paths.definition)).toBeFalse();
    expect(existsSync(paths.config)).toBeFalse();

    mkdirSync(dirname(paths.definition), { recursive: true });
    writeFileSync(paths.definition, "# Generated by thyra service install.\n");
    const uninstallCommands: string[][] = [];
    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime,
        runCommand: (argv) => {
          uninstallCommands.push(argv);
          return isWindowsTaskQuery(argv) ? 5 : 0;
        },
        log: () => undefined,
      }),
    ).toBe(5);
    expect(uninstallCommands).toHaveLength(1);
    expect(isWindowsTaskQuery(uninstallCommands[0])).toBeTrue();
    expect(existsSync(paths.definition)).toBeTrue();
  });

  test("does not restart when task-state confirmation fails", () => {
    const homeDir = tempHome();
    const executable = join(homeDir, "thyra.exe");
    const commands: string[][] = [];

    expect(
      runServiceCommand(["service", "restart"], {
        runtime: {
          platform: "win32",
          homeDir,
          appDataDir: join(homeDir, "AppData", "Roaming"),
          execPath: executable,
          argv: [executable],
        },
        runCommand: (argv) => {
          commands.push(argv);
          return isWindowsTaskWait(argv) ? 7 : 0;
        },
      }),
    ).toBe(7);
    expect(commands.some((argv) => argv[1] === "/End")).toBeTrue();
    expect(commands.some(isWindowsTaskWait)).toBeTrue();
    expect(commands.some((argv) => argv[1] === "/Run")).toBeFalse();
  });

  test("loads environment for the direct Windows task process", () => {
    const homeDir = tempHome();
    const configPath = join(homeDir, "thyra.env");
    writeFileSync(
      configPath,
      [
        "# service environment",
        "HOST=127.0.0.1",
        'export PORT="9123"',
        "HERDR_SESSION=gui-test",
      ].join("\n"),
    );
    const keys = [
      "HOST",
      "PORT",
      "HERDR_SESSION",
      "THYRA_RESTART_SUPERVISOR",
    ] as const;
    const previous = new Map(keys.map((key) => [key, process.env[key]]));

    try {
      for (const key of keys) delete process.env[key];
      expect(runServiceCommand(["service", "run", configPath])).toBe(
        SERVICE_COMMAND_CONTINUE,
      );
      expect(process.env.HOST).toBe("127.0.0.1");
      expect(process.env.PORT).toBe("9123");
      expect(process.env.HERDR_SESSION).toBe("gui-test");
      expect(process.env.THYRA_RESTART_SUPERVISOR).toBe("1");
    } finally {
      for (const [key, value] of previous) {
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
      }
    }
  });

  test("does not install a development runtime as a service", () => {
    const errors: string[] = [];
    const code = runServiceCommand(["service", "install"], {
      runtime: {
        platform: "darwin",
        homeDir: tempHome(),
        execPath: "/opt/homebrew/bin/bun",
        argv: ["/opt/homebrew/bin/bun", "src/index.ts", "service", "install"],
        uid: 501,
      },
      runCommand: () => {
        throw new Error("should not run");
      },
      error: (message) => errors.push(message),
    });

    expect(code).toBe(1);
    expect(errors.join("\n")).toContain(
      "service install requires the standalone thyra binary",
    );
  });

  test("does not bootstrap launchd when stopping the loaded job fails", () => {
    const homeDir = tempHome();
    const runtime = {
      platform: "darwin",
      homeDir,
      execPath: "/opt/thyra-test/bin/thyra",
      argv: ["/opt/thyra-test/bin/thyra"],
      uid: 501,
    };
    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand: (argv) => (argv[1] === "print" ? 1 : 0),
        log: () => undefined,
      }),
    ).toBe(0);

    let bootstrapCalled = false;
    const code = runServiceCommand(["service", "install"], {
      runtime,
      runCommand: (argv) => {
        if (argv[1] === "print") return 0;
        if (argv[1] === "bootout") return 5;
        if (argv[1] === "bootstrap") bootstrapCalled = true;
        return 0;
      },
      log: () => undefined,
    });

    expect(code).toBe(5);
    expect(bootstrapCalled).toBe(false);
  });

  test("keeps a managed systemd definition when stopping fails", () => {
    const homeDir = tempHome();
    const runtime = {
      platform: "linux",
      homeDir,
      execPath: "/opt/thyra-test/bin/thyra",
      argv: ["/opt/thyra-test/bin/thyra"],
    };
    expect(
      runServiceCommand(["service", "install"], {
        runtime,
        runCommand: () => 0,
        log: () => undefined,
      }),
    ).toBe(0);

    const definitionPath = join(
      homeDir,
      ".config",
      "systemd",
      "user",
      "thyra.service",
    );
    const code = runServiceCommand(["service", "uninstall"], {
      runtime,
      runCommand: (argv) => (argv.includes("disable") ? 1 : 0),
      log: () => undefined,
    });

    expect(code).toBe(1);
    expect(readFileSync(definitionPath, "utf8")).toContain(
      "Generated by thyra service install.",
    );
  });

  test("treats uninstall without a managed definition as a no-op", () => {
    let commandCount = 0;
    const logs: string[] = [];
    const code = runServiceCommand(["service", "uninstall"], {
      runtime: {
        platform: "linux",
        homeDir: tempHome(),
        execPath: "/opt/thyra-test/bin/thyra",
        argv: ["/opt/thyra-test/bin/thyra"],
      },
      runCommand: () => {
        commandCount += 1;
        return 0;
      },
      log: (message) => logs.push(message),
    });

    expect(code).toBe(0);
    expect(commandCount).toBe(0);
    expect(logs.join("\n")).toContain("No managed systemd service found");
  });
});

test("uninstall restores the systemd definition and permissions if daemon-reload fails", () => {
  const homeDir = tempHome();
  const paths = resolveServicePaths("systemd", homeDir);
  const definition = renderSystemdService("/opt/thyra", paths.config);
  mkdirSync(dirname(paths.definition), { recursive: true });
  mkdirSync(dirname(paths.config), { recursive: true });
  writeFileSync(paths.definition, definition);
  // Explicit, so a restrictive umask cannot turn 0640 into 0600.
  chmodSync(paths.definition, 0o640);
  writeFileSync(paths.config, "HOST=127.0.0.1\n");
  const tokenPath = join(dirname(paths.config), "auth-token");
  writeFileSync(tokenPath, "a".repeat(64));
  for (const throws of [false, true]) {
    expect(
      runServiceCommand(["service", "uninstall"], {
        runtime: {
          platform: "linux",
          homeDir,
          execPath: "/opt/thyra",
          argv: [],
        },
        runCommand: (argv) => {
          if (argv.includes("daemon-reload")) {
            expect(existsSync(paths.definition)).toBeFalse();
            if (throws) throw new Error("daemon-reload failed");
            return 7;
          }
          return 0;
        },
        log: () => undefined,
        error: () => undefined,
      }),
    ).toBe(throws ? 1 : 7);
    expect(readFileSync(paths.definition, "utf8")).toBe(definition);
    if (process.platform !== "win32")
      expect(statSync(paths.definition).mode & 0o777).toBe(0o640);
    expect(readFileSync(paths.config, "utf8")).toBe("HOST=127.0.0.1\n");
    expect(readFileSync(tokenPath, "utf8")).toBe("a".repeat(64));
    expect(
      existsSync(`${paths.definition}.uninstall-${process.pid}`),
    ).toBeFalse();
  }
});

test("service run honors an explicit supervisor override, including empty", () => {
  const homeDir = tempHome();
  const configPath = join(homeDir, "thyra.env");
  const previous = process.env.THYRA_RESTART_SUPERVISOR;
  try {
    for (const value of ["0", ""]) {
      delete process.env.THYRA_RESTART_SUPERVISOR;
      writeFileSync(configPath, `THYRA_RESTART_SUPERVISOR=${value}\n`);
      expect(runServiceCommand(["service", "run", configPath])).toBe(
        SERVICE_COMMAND_CONTINUE,
      );
      expect(process.env.THYRA_RESTART_SUPERVISOR as string | undefined).toBe(
        value,
      );
    }
  } finally {
    if (previous === undefined) delete process.env.THYRA_RESTART_SUPERVISOR;
    else process.env.THYRA_RESTART_SUPERVISOR = previous;
  }
});
