// Regenerates the bundled terminal font from Maple Mono NF CN (OFL-1.1).
//
// The CN build is ~18 MB per weight, so cn-font-split (中文网字计划) slices it
// into content-hashed woff2 chunks with unicode-range @font-face rules. The
// browser then downloads only the chunks for characters on screen. OpenType
// features are kept so programming ligatures still shape within a chunk.
//
// Usage (cn-font-split is a one-off tool, not a project dependency):
//   mkdir /tmp/cfs && cd /tmp/cfs && bun add cn-font-split@7.4.3
//   (cd node_modules/cn-font-split && node ./dist/cli.js i default)
//   CN_FONT_SPLIT=/tmp/cfs/node_modules/cn-font-split/dist/auto.mjs \
//     bun scripts/build-terminal-font.ts /usr/share/fonts/maple-mono-nf-cn

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const FAMILY = "Thyra Mono";
// [folder, font-weight, font-style, source file]
const FACES = [
  ["400", "400", "normal", "MapleMono-NF-CN-Regular.ttf"],
  ["700", "700", "normal", "MapleMono-NF-CN-Bold.ttf"],
  ["400-italic", "400", "italic", "MapleMono-NF-CN-Italic.ttf"],
] as const;

const sourceDir = process.argv[2];
if (!sourceDir) {
  console.error("usage: bun scripts/build-terminal-font.ts <maple-font-dir>");
  process.exit(1);
}
// Served as-is from /assets, where content-hashed names are cached immutably.
const URL_ROOT = "/assets/fonts/maple-mono-nf-cn";
const outRoot = resolve(import.meta.dir, `../web/public${URL_ROOT}`);
const manifestPath = resolve(
  import.meta.dir,
  "../web/src/terminalFontStylesheet.ts",
);
const { fontSplit } = await import(
  process.env.CN_FONT_SPLIT ?? "cn-font-split"
);

rmSync(outRoot, { recursive: true, force: true });
const css: string[] = [];
for (const [folder, weight, style, file] of FACES) {
  const outDir = join(outRoot, folder);
  await fontSplit({
    input: new Uint8Array(readFileSync(join(sourceDir, file))),
    outDir,
    css: {
      fontFamily: FAMILY,
      fontWeight: weight,
      fontStyle: style,
      fontDisplay: "swap",
      compress: true,
    },
    fontFeature: true,
    languageAreas: true,
    autoSubset: true,
    renameOutputFont: "[hash:10].[ext]",
    testHtml: false,
    reporter: false,
    silent: true,
  });
  const result = readFileSync(join(outDir, "result.css"), "utf8");
  // Point each chunk URL at its face folder so one stylesheet serves all.
  css.push(
    result
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/src:local\([^)]*\),/g, "src:")
      .replace(
        /url\("?\.?\/?([^")]+\.woff2)"?\)/g,
        `url("${URL_ROOT}/${folder}/$1")`,
      )
      .trim(),
  );
  rmSync(join(outDir, "result.css"));
  for (const name of readdirSync(outDir))
    if (!name.endsWith(".woff2")) rmSync(join(outDir, name), { force: true });
}
const stylesheet = `${css.join("\n")}\n`;
const hash = createHash("sha256").update(stylesheet).digest("hex").slice(0, 10);
writeFileSync(join(outRoot, `fonts-${hash}.css`), stylesheet);
writeFileSync(
  manifestPath,
  `// Generated by scripts/build-terminal-font.ts; do not edit by hand.
// Maple Mono NF CN (OFL-1.1, LICENSES/MAPLE-MONO.txt), sliced by unicode-range.
export const TERMINAL_FONT_STYLESHEET =
  "${URL_ROOT}/fonts-${hash}.css";
`,
);
console.log(`wrote ${outRoot} (${hash})`);
