// Generated by scripts/build-terminal-font.ts; do not edit by hand.
// Maple Mono NF CN (OFL-1.1, LICENSES/MAPLE-MONO.txt), sliced by unicode-range.
export const TERMINAL_FONT_STYLESHEET =
  "/assets/fonts/maple-mono-nf-cn/fonts-385fb7d039.css";
