// Generated by scripts/build-terminal-font-presets.py; do not edit by hand.
// Self-hosted terminal font presets (OFL-1.1, see THIRD_PARTY_NOTICES.md):
// the family, then the /assets/fonts/presets/<preset>/ faces, regular first.
export const TERMINAL_FONT_PRESET_FILES: Record<string, string[]> = {
  "jetbrains-mono": [
    "JetBrains Mono",
    "Regular-c0a0eaf9ec",
    "Bold-1956c23afa",
    "Italic-a40c0be732",
    "BoldItalic-7d17830222",
  ],
  "fira-code": ["Fira Code", "Regular-65c2e8f25a", "Bold-fec817d2d2"],
  "cascadia-mono": [
    "Cascadia Mono",
    "Regular-dd573ca6b6",
    "Bold-0774f4c8f1",
    "Italic-2944c8b319",
    "BoldItalic-e6b5ae8120",
  ],
  iosevka: [
    "Iosevka Term",
    "Regular-ada1df1af6",
    "Bold-231849e757",
    "Italic-951e663f7c",
    "BoldItalic-1eecf1ccb1",
  ],
  "source-code-pro": [
    "Source Code Pro",
    "Regular-b4db9c1093",
    "Bold-e92f22da99",
    "Italic-1ee4e9afb0",
    "BoldItalic-b2fd7ef1f3",
  ],
  "ibm-plex-mono": [
    "IBM Plex Mono",
    "Regular-f05fb22e71",
    "Bold-6b4ea2bb13",
    "Italic-24c28662e5",
    "BoldItalic-2c95c53033",
  ],
  "noto-sans-mono": ["Noto Sans Mono", "Regular-222ab66dce", "Bold-5b6e55b8a9"],
};
